arch: NestedUNet
batch_size: 8
cfg: null
dataset: /opt/data/private/wzf/u_shapley/dsb-unet++/dsb2018_96/
debug: false
deep_supervision: false
early_stopping: -1
epochs: 400
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_h: 96
input_w: 96
loss: BCEDiceLoss
lr: 0.001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: dsb_NestedUNet_pretrain40
nesterov: false
num_classes: 1
num_workers: 4
optimizer: Adam
patience: 2
pretrain: false
pretrain_path: null
pruning: false
pruning_percentage: 0.3
sample_ratio: null
scheduler: CosineAnnealingLR
strategy: random
weight_decay: 0.0001
