arch: UNet
batch_size: 8
cfg: null
dataset: /opt/data/private/wzf/u_shapley/BUSI_all
debug: false
deep_supervision: false
early_stopping: -1
epochs: 400
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_h: 256
input_w: 256
loss: BCEDiceLoss
lr: 0.001
mask_ext: _mask.png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: pretrain_400_unet_shuffle_normalize
nesterov: false
num_classes: 1
num_workers: 4
optimizer: Adam
patience: 2
pretrain: false
pretrain_path: null
pruning: false
pruning_percentage: 0.3
sample_ratio: null
scheduler: CosineAnnealingLR
strategy: random
weight_decay: 0.0001
